name: GapplePerms
main: com.github.arsenalfcgunners.gappleperms.GapplePerms
version: 1.1
commands:
   promote:
      description: Promotes a player to a higher rank.
      usage: /<command>
   demote:
      description: demotes a player to a higher rank.
      usage: /<command>
   permission:
      description: Manages the permissions of a rank.
      usage: /<command>
   rank:
      description: Manages the permissions of a rank.
      usage: /<command>
   resetdb:
      description: Resets the player ranks databse.
      usage: /<command>

Permissions:
  gappleperms.admin:
    description: Allows the player to manages ranks.
